### ISSUE TITLE
Display new packages somewhere in the website

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#108]
It would be nice to see which packages get promoted from AUR to community or core/extra, or even the new packages in the distro. I think it would be something interesting to have because promoted packages are probably new good software that would be interesting to hear about.This could simply be implemented as a "new" icon next to new packages in the "recently updated packages" box, similarly to what the AUR home page has.

Relevant forum discussion: http://bbs.archlinux.org/viewtopic.php?id=66071

**Comment by jelly** [comment]
A [wip](https://github.com/jelly/archweb/tree/added_removed_rss) branch is available here.

**Comment by z3ntu** [comment]
This seems to be covered by 2f555364
