### ISSUE TITLE
Missing required by for python-qt.py

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#193]
[python-qt.py](https://www.archlinux.org/packages/community/any/python-qt.py/) is required by [qspectrumanalyzer](https://www.archlinux.org/packages/community/any/qspectrumanalyzer/) but not listed in the python-qt.py page.

**Comment by felixonmars** [comment]
I tried to make a test case to reproduce the issue, but unfortunately it just passes.

In case it's helpful for anyone who wants to work on this subject later: https://paste.xinu.at/tDi/

**Comment by jelly** [comment]
After more investigation, this works fine on our [staging](https://archweb-dev.archlinux.org/packages/community/any/python-qt.py/) env. Where it has:
```
select * from packages_depend where name = 'qspectrumanalyzer';
   id    |     name     | version | comparison | description | deptype | pkg_id 
---------+--------------+---------+------------+-------------+---------+--------
 8760044 | python-qt.py |         |            |             | D       | 370402
```

And on our live instance this relation is missing, since reporead makes the relations it could be that it crashed / stopped halfway through.

**Comment by jelly** [comment]
Closing, unable to reproduce.
