### ISSUE TITLE
Inline script blocked by CSP

### ISSUE THREAD

**Issue by SibrenVasse** [archlinux/archweb#202]
See [packages/package_details.html:33](https://github.com/archlinux/archweb/blob/5e30720fce032393b581575e05531178b44414fc/templates/packages/package_details.html#L35)

Maybe just remove the inline script and add target="_blank" to the \<a\>?

EDIT:
Similar thing happens in the django admin. When changing user {permissions, groups}, SelectBox.js tries to apply an inline style. This causes the change to the user to fail.

**Comment by jelly** [comment]
Opening a separate window as a form of a popup is kinda silly, opening it as a new tab would be ok. The django admin issue however should be fixed in Django.
