### ISSUE TITLE
why there is no mention about GNU on Arch Linux's website's front page? 

### ISSUE THREAD

**Issue by catastrop** [archlinux/archweb#221]

**Comment by jelly** [comment]
Arch is not a pure GNU distro nor does GNU even recognise us since we are quite liberal with software we package in our repositories (ie. steam, etc.)

**Comment by eli-schwartz** [comment]
https://en.wikipedia.org/wiki/GNU/Linux_naming_controversy#Opinions_supporting_%22Linux%22

**Comment by AladW** [comment]
GNU/systemd/yaourt
