### ISSUE TITLE
`limit` parameter doesn't accept more than 250 results.

### ISSUE THREAD

**Issue by Edu4rdSHL** [archlinux/archweb#235]
I'm writing a tool to track packages removed from official repository's but when interacting with the API, the limit parameter can't be increased more than 250 results. It's hard to write a tool with that limitation actually because I'm going to track entire repos, I can just look for only a repo and reduce the number of output but for example, `extra` have 2927 packages at the moment. Trying with something like `&limit=-1` ends in a internal error.

IThere are the querys that I'm actually trying to do:

```
# The limit continues at 250

https://www.archlinux.org/packages/search/json/?&repo=Community&repo=Extra&limit=2000
```

```
# Ends in a 500 Internal server error

https://www.archlinux.org/packages/search/json/?&repo=Community&repo=Extra&limit=-1
```

**Comment by falconindy** [comment]
https://www.archlinux.org/feeds/packages/removed/all/community/ seems more appropriate then trying to scrape an entire repo at a time from an API endpoint.

**Comment by Edu4rdSHL** [comment]
Yeah, also better. Thank you.
