### ISSUE TITLE
aur.archlinux.org not available from Iran

### ISSUE THREAD

**Issue by saeedghollami** [archlinux/archweb#237]
Since Aug 27, aur.archlinux.org is not available from Iran. If I search a package with a pacman wrapper like yay I get this error:

`$ yay -Ss sublime`
`Error during AUR search: Get https://aur.archlinux.org/rpc.php?arg=sublime&type=search&v=5: net/http: TLS handshake timeout
Showing Repo packages only`

If I ping aur.archlinux.org it sends 4 packages and stop!!

`$ ping aur.archlinux.org `
`PING aur.archlinux.org (5.9.250.164) 56(84) bytes of data.
64 bytes from aur.archlinux.org (5.9.250.164): icmp_seq=1 ttl=53 time=142 ms
64 bytes from aur.archlinux.org (5.9.250.164): icmp_seq=2 ttl=53 time=141 ms
64 bytes from aur.archlinux.org (5.9.250.164): icmp_seq=3 ttl=53 time=142 ms
64 bytes from aur.archlinux.org (5.9.250.164): icmp_seq=4 ttl=53 time=138 ms
`
I wonder what happened, the arch AUR banned Iranian usrs ? or AUR moved to a server which already banned us like AWS cloud and google cloud. 
The other possibility here is the Iran government banned AUR which we already send issue for them but they claim we didn't banned AUR

**Comment by jelly** [comment]
Please don't make an issue here, it is not about the AUR. What if you browse with a webbrowser to aur.archlinux.org?

**Comment by barthalion** [comment]
It's going to be hard to help if you don't give us `traceroute aur.archlinux.org` output and your external IP address.

**Comment by jelly** [comment]
@barthalion reported on https://www.reddit.com/r/archlinux/comments/cwziz4/have_arch_packages_banned_for_iranian_users/eyi9eot/

**Comment by saeedghollami** [comment]
It's start to working again.
