### ISSUE TITLE
Consider adding an asset preprocessor/task runner like gulp or webpack

### ISSUE THREAD

**Issue by Phosphenius** [archlinux/archweb#249]
I'd like to give #212 a try and my first step would be to add a module bundler like Webpack to makes things easier and also faster by using SCSS/LESS, asset minification etc. This would also allow to pull in dependencies like jQuery via npm instead of adding them directly to the repo like it's the case now. 

Would this be a welcome change?

**Comment by jelly** [comment]
I do not believe we really need less or scss, our non minified css file is 3.4 Kb compressed. The CSS file is only just ~ 1100 lines. As for asset management via npm, again it does not add much and I would love to get rid of jQuery in the future, but I need it for the tablesorter plugin and d3js.

**Comment by Phosphenius** [comment]
Fair points, I'd argue though that LESS/SCSS makes the CSS less redundant and easier to maintain (think variables for sizes, colors etc.). Maybe this can be considered when the frontend gets a relaunch/rework or something.
