### ISSUE TITLE
Requirement psycopg2==2.7.4 doesn't support Python 3.8

### ISSUE THREAD

**Issue by z3ntu** [archlinux/archweb#259]
See https://github.com/psycopg/psycopg2/issues/854 , the issue was fixed for psycopg2 2.8 but requirements_prod.txt still declares 2.7.4 as being required.

Backporting that patch to 2.7.4 and building that seems to work fine.

**Comment by jelly** [comment]
True, we use virtualenv --system-site-packages on our live env we should probably remove psycopg from the requirements file.

**Comment by jelly** [comment]
Done in 6507d02ca978ef10afd8790f3acf0fc3f61253b5
