### ISSUE TITLE
PEP8 the whole project

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#287]
A lot of functions don't have enough blank lines or too many blank lines, so we should fix this with a PEP8 ci check and fix all the code!

**Comment by dvzrv** [comment]
How about applying black on the entire code base? This can also conveniently be used to do compliance checks on pull requests.

**Comment by just1602** [comment]
I could this one a try, but do you want to use something like `flake8` or other pep8 validator or should I run black on the coe, then write a ci check and a pre-push git hook using `black --diff` ?

**Comment by dvzrv** [comment]
flake8 sounds about right

**Comment by jelly** [comment]
black fixes a lot of formatting nicely, however I do not agree with it's string opinions such as preferring " over '. The same goes with PEP8 and line length choices

**Comment by dvzrv** [comment]
line length is configurable (also for black).
I'm not sure about the configureability for string preferences, but I can live with " over ' any day of the week. ;-)
