### ISSUE TITLE
Add WKD line for Download template

### ISSUE THREAD

**Issue by Foxboron** [archlinux/archweb#340]
The release model should be extended with an email field for "Web Key Directory Lookup".

https://github.com/archlinux/archweb/blob/master/releng/models.py#L16

This should be displayed in the template if present with the following: `gpg --auto-key-locate clear,wkd -v --locate-external-key {release.wkd_email}`.

https://github.com/archlinux/archweb/blob/master/templates/public/download.html#L103-L109

For Pierre it should be `gpg --auto-key-locate clear,wkd -v --locate-external-key pierre@archlinux.de`

The reason is that looking up gpg key ids with keyservers are complicated and substantially easier with WKD which Arch Linux deploys these days.

**Comment by fish-dango** [comment]
I can take a try here!

**Comment by Foxboron** [comment]
@fish-dango Please do :)

**Comment by jelly** [comment]
Fixed in 68b734e81728fef83a7ed0b5ec18af2931e2f3c8
