### ISSUE TITLE
PGP fingerprint link text should show full fingerprint

### ISSUE THREAD

**Issue by heftig** [archlinux/archweb#346]
The text of PGP fingerprint links is currently "0x01234567", which looks a bit untrustworthy. It should show the full fingerprint, i.e. the text should be "0000&nbsp;1111&nbsp;2222&nbsp;3333&nbsp;4444&emsp;5555&nbsp;6666&nbsp;7777&nbsp;8888&nbsp;9999".

The digits are in groups of four, with a larger space (e.g. `&emsp;`) in the middle. Maybe it's possible to use styled markup instead so that copying the fingerprint gets you a string without spaces.

**Comment by jelly** [comment]
So if I understand it correctly you want the keys listed on the Developer/Trusted user pages to be formatted as following:

![image](https://user-images.githubusercontent.com/67428/126451306-502f48bc-d028-4c7d-b45d-5e229ed2be93.png)

For easier copy pasting we could add some JavaScript to the page with a button to copy paste either the key or the full command like:

```
gpg --recv-keys 0xE499C79F53C96A54E572FEE1C06086337C50773E
```

Or prefer fetching via WKD

```
gpg --auto-key-locate clear,wkd -v --locate-external-key jelle@archlinux.org
```
But not everyone might have the correct email address configured.

**Comment by dvzrv** [comment]
I would also be okay with just providing the "long" format (e.g. `gpg --keyid-format long --list-keys <uid> | sed -n 's/^[ \t]*//g; 2,2p'`) directly and not going for the fingerprinted (tuple style) version.
That way we don't need any additional modification or js to be able to copy the key from the website (text selection just works).
