### ISSUE TITLE
Allow searching for multiple packages in one request

### ISSUE THREAD

**Issue by hwittenborn** [archlinux/archweb#348]
The AUR RPC interface supports multiple queries to be specified (`?arg[]=package`), but I haven't found anything similar with the Arch Repository JSON interface.

My use case is requiring searching for an unknown user-defined amount of packages, so ideally I can try to limit making a ton of requests to limit time overhead.

**Comment by jelly** [comment]
Archweb does not really have an API which is unusable for consumers, so this is something for https://github.com/archlinux/archweb/issues/199

**Comment by hwittenborn** [comment]
Just a heads up in case it influences anything, but I'm not really needing the aforementioned functionality anymore.

My use case has since Ben seized, so it's not really going to affect me one way or the other if this doesn't get done.
