### ISSUE TITLE
Change the RSS icon to match the one on the AUR

### ISSUE THREAD

**Issue by hwittenborn** [archlinux/archweb#367]
The RSS icons on the Arch Linux homepage currently look like this:

![image](https://user-images.githubusercontent.com/74838472/129451324-2d38051c-2bd6-4c32-bfb4-48fa47147a51.png)

While the ones on the AUR look like so:

![image](https://user-images.githubusercontent.com/74838472/129451354-7c43c5b0-a944-4ae5-93d9-ac36edb382e7.png)

I feel like the ones for the Arch Linux homepage should be changed to match those on the AUR, as they match and fit in a lot better.

**Comment by jelly** [comment]
Sounds good to me.
