### ISSUE TITLE
Add <Author> to planet feed

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#377]
The `author_name` can be set in our `feeds.py` PlanetFeed model.

https://docs.djangoproject.com/en/3.2/ref/contrib/syndication/

**Comment by gregoiredx** [comment]
Hi @jelly, here is an implementation proposition for this: https://github.com/archlinux/archweb/pull/384.
Let me know what you think :slightly_smiling_face:

**Comment by jelly** [comment]
Implemented in https://github.com/archlinux/archweb/pull/384
