### ISSUE TITLE
Add a section with crypto donations

### ISSUE THREAD

**Issue by donBarbos** [archlinux/archweb#429]
reasons to add this section:
* current methods (like PayPal) take high fees
* we all have different levels of access to traditional financial institutions
* some people don't want to sponsor intermediaries by fees
* some people don't want to reveal their identity

found a discussion on ArchWiki forum: [link](https://bbs.archlinux.org/viewtopic.php?id=274032)

**Comment by jelly** [comment]
This is not something which should be discussed on the issue tracker for the website as it is a project issue. Our funds are currently handled by SPI which also handles our donations, in that sense we are limited in what we can provide.

It is up to our project leader @anthraxx if we want to have a non SPI crypto alternative.
