### ISSUE TITLE
[feat] security

### ISSUE THREAD

**Issue by loynoir** [archlinux/archweb#437]
### Thought
Just came up with a question, did archlinux pacman drop md5 support or show warning?

https://github.com/search?q=org%3Aarchlinux+md5sums%3D&type=code

Seems not.

MD5 is not secure now. There seems to be `md5collgen` to generate same MD5.

### Feat
- Drop all md5sums in current codebase.
- If makepkg using md5sums, show warning.

**Comment by kpcyrd** [comment]
There's an ongoing effort to fix all packages that rely exclusively on md5sums= or sha1sums= from PKGBUILDs: https://archlinux.org/todo/deprecate-md5-and-sha1-in-community/

This is already done for [community] and [multilib]. If you're interested in things like this you might also be interested in https://github.com/kpcyrd/archlinux-inputs-fsck. :)

**Comment by jelly** [comment]
This has nothing to do with the Arch Linux website, note that the md5sum is used as a checksum and it does not offer any security at all, only cryptographically signing the artifacts would offer any security guarrentees.
