### ISSUE TITLE
Git support

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#438]
Support our new Git repository layout.

**Comment by jelly** [comment]
What in archweb is svn specific?

### svn_root

Every repository has an `svn_root` set used to link to packages and find stuff for example for `Community` it is `community`.

How do we link to packages in Git?

This will become a separate Gitlab repo per `pkgbase` such as:

https://gitlab.archlinux.org/archlinux/packaging/packages/$pkgbase

@anthraxx did we have an example import somewhere in Gitlab?

As all packages end up here, we can just remove `svn_root`. Who knows what will happen to `kde-unstable` and `gnome-unstable`? @felixonmars 

### populate signoffs

The [signoffs](https://archlinux.org/packages/signoffs/) page uses `./manage.py populate_signoffs` which pulls the latest commit message from SVN for a given package that is signoff-eliligable using `svn log --limit=1 --xml $path`.

So now we'll have to fetch the last git commit of $pkgbase, which should be a predictable URL. However can we easily fetch the last Git commit without cloning the whole repo?

**Comment by jelly** [comment]
For `populate_signoffs` we should use [Gitlab's commit API](https://docs.gitlab.com/ee/api/commits.html) or tags API.

curl "https://gitlab.archlinux.org/api/v4/projects/archlinux%2finfrastructure/repository/commits" | jq | less

curl "https://gitlab.archlinux.org/api/v4/projects/archlinux%2finfrastructure/repository/tags" | jq | less

Note that we probably want to use a API token as surely the endpoint is rate limited.

**Comment by jelly** [comment]
https://github.com/archlinux/archweb/pull/446

**Comment by anthraxx** [comment]
I think we can clone this issue now, right? Please re-open if I'm being silly.
