### ISSUE TITLE
todolists - information loss since git migration

### ISSUE THREAD

**Issue by Toolybird** [archlinux/archweb#465]
Just a heads-up in case it matters (it probably doesn't). Please compare [1] and [2]. Probably nothing can be done about it anyway...

[1] https://archlinux.org/todo/invalid-mtree-files/
[2] https://web.archive.org/web/20230320100145/https://archlinux.org/todo/invalid-mtree-files/

**Comment by polyzen** [comment]
The todo lists have to be re-saved so it can pick up the packages in their new repos. Did so for this todo and marked them all completed. I would like to think this has been done for lists that were incomplete already, but don't know.

**Comment by jelly** [comment]
Re-saving will lose completed / incompleted status. I could of course fix that but I kinda inclined to do nothing as there is not much value in old todo's.
