### ISSUE TITLE
[packages] "Bug Reports"/"Add New Bug" package actions use the wrong project id

### ISSUE THREAD

**Issue by emanuele6** [archlinux/archweb#466]
Yesterday, I reported a bug for [extra/pt2-clone](https://archlinux.org/packages/extra/x86_64/pt2-clone/) using the "Add New Bug" action: https://bugs.archlinux.org/task/78624

A few minutes later, an operator changed a bunch of fields for my report and assigned the task to the package's maintainer, one of the fields they changed was:
```
Field changed: Attached to Project (Arch Linux → Community Packages)
```

Now, I have noticed that if I click on the "Bug Reports" action from [extra/pt2-clone](https://archlinux.org/packages/extra/x86_64/pt2-clone/) I can't see the report anymore.

The problem seems to be that both the "Add New Bug" and "Bug Reports" links are using `project=1` in their URL's query. The project with id 1 seems to be "Arch Linux", "Community Packages" has id 2.

So reports for community packages created with "Add New Bug" will be part of the "Arch Linux" project instead of "Community Packages", and if that field is corrected, those bug reports will be "hidden" form the page linked by "Bug Reports".

Those project actions should probably be updated to use the correct project id on "extra" packages pages: for "Add New Bug", so that reports are automatically created on the correct project; and, especially for "Bug Reports", so that, when operators correct tasks' project field, they don't accidentally "hide" them.

o/
&nbsp;emanuele6

**Comment by Toolybird** [comment]
By way of clarification, the flyspray bug tracker is still on the old legacy layout. The practical implication of this is: there are 2 groups of Package Maintainers. All the old "TU's" as they were known are attached to the "Community" sub-project. Therefore, to assign tickets to the correct PM's for pkgs which used to be in [community], I have to move those tickets to the "Community" sub-project. It's no problem for me currently...so I wouldn't bother spending too much effort on this. Obviously, it all becomes irrelevant when we eventually give flyspray the flick :)

**Comment by emanuele6** [comment]
> Therefore, to assign tickets to the correct PM's for pkgs which used to be in [community], I have to move those tickets to the "Community" sub-project. It's no problem for me currently...so I wouldn't bother spending too much effort on this.

But if you do that, then users cannot find bug reports for packages by clicking on the "Bug Reports" action on package pages
![file](https://github.com/archlinux/archweb/assets/20175435/bd35614e-7bfa-4c67-beb3-4221ede0221e)

There may be dozens of reports, but they won't see any; and the bug they want to report may already have been reported, and they will report a duplicate. :/

**Comment by Toolybird** [comment]
> then users cannot find bug reports for packages by clicking on the "Bug Reports" action

It's a good point! I guess I personally never use that function and just always query the bug tracker directly.

**Comment by emanuele6** [comment]
![file](https://github.com/archlinux/archweb/assets/20175435/ec82e602-0179-403d-b9b9-7e002ff664d4)
It happened again. Users cannot tell if they are reporting a duplicate issue because issues keep getting moved to an unreachable category, and the package shows up as having no issues...

**Comment by jelly** [comment]
> It happened again. https://bugs.archlinux.org/task/79172 ![file](https://user-images.githubusercontent.com/20175435/255354148-ec82e602-0179-403d-b9b9-7e002ff664d4.png)
> 
> Users cannot tell if they are reporting a duplicate issue because issues keep getting moved to an unreachable category, and the package shows up as having no issues...

What happened again?

We have one project for reporting bugs now, which is the "Arch Linux" category and every bug link should use that now?

If your issue is that you reported an issue duplicate because it was also in the "Community" category then I can't help because that category is closed now.

In the end, we are working towards closing down the flyspray bug tracker so this is not something we should invest time in.
