### ISSUE TITLE
ArchLinux Planet RSS and view don't align

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [archlinux/archweb#493]
Right now if I go https://archlinux.org/planet/ I see these posts:
* [Join the Arch Testing Team - Call for participation](https://bbs.archlinux.org/viewtopic.php?id=293464)
* [mkinitcpio hook migration and early microcode](https://archlinux.org/news/mkinitcpio-hook-migration-and-early-microcode/)
* [My FOSDEM 2024 Experience](https://blog.orhun.dev/fosdem-2024-experience/)
* [January](https://monthly-reports.archlinux.page/2024/01/)

However if I download the RSS at https://archlinux.org/feeds/planet/ I get this:
* [Join the Arch Testing Team - Call for participation](https://bbs.archlinux.org/viewtopic.php?id=293464)
* [mkinitcpio hook migration and early microcode](https://archlinux.org/news/mkinitcpio-hook-migration-and-early-microcode/)
* [Uninterupted desktop streaming vs. NetworkManager](https://rubin55.org/blog/uninterupted-desktop-streaming-vs-network-manager/)
* [My FOSDEM 2024 Experience](https://blog.orhun.dev/fosdem-2024-experience/)
* [January](https://monthly-reports.archlinux.page/2024/01/)

Now Rubin Simons insightful post about the shortcomings of NetworkManger comes up.
I also noticed his RSS feed doesn't show up in the "Subscriptions" column to the right at https://archlinux.org/planet/.

Relevant code:
* https://github.com/archlinux/archweb/blob/master/feeds.py#L398-L436
* https://github.com/archlinux/archweb/blob/master/planet/models.py

**Comment by jelly** [comment]
That's due to https://github.com/archlinux/archweb/commit/6ccd4a2fa928c83f2bb3768631f4ff342ecd21f8 we only want staff to post on the planet.
