### ISSUE TITLE
Always "create" a hedgedoc link per To Do list

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#495]
We have To Do lists already and want to have additional notes for why a package is broken or a link to patches and more information or allow others to collaborate easily.

In a ToDo for [example](https://archlinux.org/todo/rebuild-core-with-reproducible-pacman/) there should be a link with `packager notes for todo` which links to [hedgedoc](https://md.archlinux.org/todo-rebuild-core-with-reproducible-pacman) a pad is automatically created on hedgedoc's side when someone with enough permissions (an Arch Linux packager) opens it.

Optionally it would be great to set permissions automatically to allow externals to view the pad as pads are private by default (for a good reason).

**Comment by amns13** [comment]
Hi @jelly! I want to work on this issue and had a question. There is already a hedgedoc link in  the todo page with `Todo Notes` link name. As part of this issue, do we want to add a similar entry for each package listed in the table below?

Apologies, if this was supposed to be obvious, this is my first time contributing on this project and did not want to create a PR based on just my assumptions. Thanks.

**Comment by jelly** [comment]
Hi, thanks for asking! This is indeed already implemented, sorry for the confusion I'll close it now.
