### ISSUE TITLE
Logout no longer works

### ISSUE THREAD

**Issue by yan12125** [archlinux/archweb#511]
Login works fine. However, when I clicked Logout, it shows an empty page, and I see an `HTTP/2 405` error in Firefox devtools.

**Comment by jelly** [comment]
The logout button does a GET and it re-uses and calls a Django internal function which has this lovely comment:

```
    # RemovedInDjango50Warning: when the deprecation ends, remove "get" and
    # "head" from http_method_names.
    http_method_names = ["get", "head", "post", "options"]
```

**Comment by jelly** [comment]
> Support for logging out via GET requests in the django.contrib.auth.views.LogoutView and django.contrib.auth.views.logout_then_login() is removed.

With no alternative mentioned.
