### ISSUE TITLE
https://archlinux.org/packages/ systematically shows wrong dependencies, package contents, so-names and required-bys

### ISSUE THREAD

**Issue by hardfalcon** [archlinux/archweb#516]
Note: This issue was originally filed at https://gitlab.archlinux.org/archlinux/infrastructure/-/issues/604, but it probably belongs into here.

It appears that for any package that I open on https://archlinux.org/packages/, the dependencies, package contents, so-names and required-bys of another package are shown.

For example, https://archlinux.org/packages/extra/x86_64/a2jmidid/ shows the dependencies, package contents, so-names and required-bys of `sbsigntools` instead of the ones for `a2jmidid`.

Also, it appears that any time I load the `/files/` page of a package (for example https://archlinux.org/packages/extra/x86_64/a2jmidid/files/), the (wrong) package whose dependencies, package contents, so-names and required-bys are shown on the "main" package page (for example https://archlinux.org/packages/extra/x86_64/a2jmidid/) changes, even though the `/files/` page will actually show the package contents of the *correct* package.

**Comment by Toolybird** [comment]
Yep, noticed the same thing and was just about to file an issue.. something is definitely amiss.

**Comment by HanabishiRecca** [comment]
I noticed it yesterday. But hold filling the issue at the time with assumption that it could be temporary internal shenanegans.

**Comment by jelly** [comment]
It's due to https://github.com/archlinux/archweb/pull/513/commits/86d624d2ffce98d8d9f48cc25ec9ac918f3b494c
