### ISSUE TITLE
ISO 8601 date format

### ISSUE THREAD

**Issue by micwoj92** [archlinux/archweb#520]
Hello,

Previously (up until around the [outage](https://old.reddit.com/r/archlinux/comments/1e6n0w1/arch_website_appears_to_be_down/)) packages page used to show dates in ISO 8601 format as can be seen on this snapshot https://web.archive.org/web/20240718044236/https://archlinux.org/packages/
After the outage it uses month day, year format https://web.archive.org/web/20240720124233/https://archlinux.org/packages/

Was there anything changed? Could it be reverted back to ISO 8601, thanks.

**Comment by jelly** [comment]
And https://web.archive.org/web/20231204002243/https://archlinux.org/packages/extra/any/perl-test-most/ and https://archlinux.org/packages/extra/any/perl-test-most/

I don't believe this is a recent change. Maybe more something to do with Django 5.

**Comment by micwoj92** [comment]
Actually it affects entire site. I will update title of the issue.

I don't know if it is new Django version. I had similar issue 2 years ago, but it went away shortly.
https://old.reddit.com/r/archlinux/comments/rknkx5/date_change_on_website/

**Comment by nl6720** [comment]
Quoting https://forum.djangoproject.com/t/datetime-format/30811/10:

> There was a change in the docs between 4.2 and 5.0 that may explain your situation.
> 
> In 4.2, DATETIME_FORMAT:
> 
>> Note that if [USE_L10N](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-USE_L10N) is set to True , then the locale-dictated format has higher precedence and will be applied instead.
> 
> Since the [USE_L10N setting was removed in 5.0 5](https://docs.djangoproject.com/en/5.0/releases/5.0/#features-removed-in-5-0), the docs now read:
> 
>> Note that the locale-dictated format has higher precedence and will be applied instead.
> 
> (In other words, locale-defined formats always take precedence.)
> 
> This means that you either need to change the locale format, or specifically use this format in the template.

**Comment by nl6720** [comment]
I don't know what is the proper way to fix this, but replacing `date:"DATETIME_FORMAT"` with `date:"Y-m-d H:i"` works.

**Comment by micwoj92** [comment]
Sorry for late ping @nl6720, I Must have missed email for this closure.
It is still not 100% ISO 8601 as it was. For example ood flags are not in this format:
https://archlinux.org/packages/extra/x86_64/librime/
Same with /packages and /news:
https://archlinux.org/packages
https://archlinux.org/news/

Quick search can show difference between package details and packages page:
https://github.com/search?q=repo%3Aarchlinux%2Farchweb%20pkg.build_date%7Cdate&type=code
