### ISSUE TITLE
Problem navigating archlinux.org

### ISSUE THREAD

**Issue by atabrkata** [archlinux/archweb#528]
For some time now( maybe a month or so), i can't navigate archlinux.org properly. Here is what happens;

Open a browser, any browser (on any OS)
type archlinux.org  and enter,
Page loads instantly.
Click any link within the page  >> new link won't open for about 2 mins (on average).
if and when the link opens, click another link from within the loaded page >> same cycle.

Say if a link is opened and loaded for more than 2 mins waiting on a browser tab.
Click any link from within the page, link opens and loads instantly. 

I don't have any problem loading any other web page, my internet is stable.

Using vpn, the problem goes away. So i think this is regional.

**Comment by jelly** [comment]
If this is an issue with your ISP, there isn't much we can do.
